### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by Samikshya-Maharjan** [venawm/RentalX#1]
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/107391117/228414698-ae45ee2e-0965-4464-973c-0cfebe588bfa.png">
![image](https://user-images.githubusercontent.com/107391117/228415098-3e37d9e4-a223-428f-9386-fc8b6c259aa9.png)

When clicking on View more option while viewing more cars, its showing blank and not being able to click anywhere.

**Comment by venawm** [comment]
issue fixed in Commit 14 minor fixes 1.3
