### ISSUE TITLE
Add cars not working

### ISSUE THREAD

**Issue by Samikshya-Maharjan** [venawm/RentalX#3]
when you add a car, it is showing uploaded successfully but is not added while viewing from available products, 

does it take time or is it an error? 

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/107391117/236657993-c260d599-4099-421d-a332-1daf9754fecc.png">
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/107391117/236658001-c570aa8c-46c9-4bc5-9ba3-c0a2a09345d1.png">

**Comment by venawm** [comment]
It takes time for the image api to be returned by the server as we are using free image hosting server cloudinary.
